import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";

import Header from "@/component/Header";
import Footer from "@/component/Footer";
import "swiper/css";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-poppins",
//   display: "swap",
// });
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-open-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.variable}>
      <body className="antialiased" style={{fontFamily:'Open Sans", sans-serif'}}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
